server:
  port: 9090
  
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: dushyant
    url: jdbc:mysql://localhost:3306/usermanagement
    username: dushyant
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

